### ISSUE TITLE
ValueError: 'home_event' is not a valid value for signal;

### ISSUE THREAD

**Issue by Estelle-Ledoux** [smerkel/maudESGEdit#1]
When running the maudESGEdit.py script in python, I ran into the issue : 

ValueError: 'home_event' is not a valid value for signal; supported values are 'resize_event', 'draw_event', 'key_press_event', 'key_release_event', 'button_press_event', 'button_release_event', 'scroll_event', 'motion_notify_event', 'pick_event', 'figure_enter_event', 'figure_leave_event', 'axes_enter_event', 'axes_leave_event', 'close_event'

It seems like it is a matplotlib version issue as proposed here : https://stackoverflow.com/questions/73937679/matplotlib-error-valueerror-home-event-is-not-a-valid-value-for-signal

Downgrading matplotlib to a version older than 3.6.0 worked for me.

**Comment by smerkel** [comment]
This was a leftover from an older version of the code. This section has now been removed and the code should work on most versions of matplotlib.
